import { expect, test } from '@playwright/test'

test('игра сохраняется под настройками, а выбор способа сворачивания переживает перезагрузку', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать историю' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionUrl = page.url()
  const sidebar = page.locator('[data-slot="sidebar"][data-side="left"]')
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await expect(sidebar).toHaveAttribute('data-collapsible', 'offcanvas')

  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('button', { name: 'Настройки' }).click()
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toBeVisible()
  expect(page.url()).toBe(sessionUrl)
  await page.getByRole('switch', { name: 'Показывать иконки при сворачивании' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Свернуть навигацию' }).click()
  await expect(sidebar).toHaveAttribute('data-collapsible', 'icon')
  await expect(page.locator('[data-slot="sidebar-header"]')).toBeHidden()
  await page.reload()
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await expect(sidebar).toHaveAttribute('data-collapsible', 'icon')

  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('link', { name: 'Персонажи' }).click()
  await expect(page.getByRole('heading', { name: 'Аканэ' })).toBeVisible()
  await page.getByRole('link', { name: 'Настройки' }).click()
  await expect(page.getByRole('heading', { name: 'Настройки' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('на узком экране навигация открывается поверх новеллы и закрывается после перехода', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать историю' }).click()
  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await expect(page.locator('[data-mobile="true"]')).toBeVisible()
  await page.getByRole('link', { name: 'Персонажи' }).click()
  await expect(page.getByRole('heading', { name: 'Персонажи' })).toBeVisible()
  await expect(page.locator('[data-mobile="true"]')).toHaveCount(0)
})

test('настройки поверх тестовой сцены не сбрасывают инспектор автора', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать историю' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  await expect(page).toHaveURL(/\/studio\/[^/]+$/)
  const sessionUrl = page.url()
  const inspector = page.getByRole('complementary', { name: 'Инспектор сессии' })
  await expect(inspector).toBeVisible()
  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('button', { name: 'Настройки' }).click()
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toBeVisible()
  expect(page.url()).toBe(sessionUrl)
  await page.keyboard.press('Escape')
  await expect(inspector).toBeVisible()
})
