import { expect, test } from '@playwright/test'

test('режим сцены скрывает интерфейс и возвращает его кликом без потери набранного действия', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionUrl = page.url()
  await page.getByRole('textbox', { name: 'Ваше действие' }).fill('Осмотреть улицу')
  await page.getByRole('button', { name: 'Скрыть интерфейс' }).click()

  await expect(page.locator('[data-slot="sidebar-wrapper"]')).toHaveAttribute('data-cinematic', 'true')
  await expect(page.getByRole('region', { name: 'Игровая сцена' }).locator('.scene-background')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Игровая сцена' }).locator('.character-sprite')).toBeVisible()
  await expect(page.locator('.game-header')).toBeHidden()
  await expect(page.locator('.dialogue')).toBeHidden()
  await expect(page.locator('[data-slot="sidebar-trigger"]')).toBeHidden()
  await expect(page.locator('[data-slot="sidebar"]')).toBeHidden()

  await page.mouse.click(250, 250)
  await expect(page.locator('[data-slot="sidebar-wrapper"]')).not.toHaveAttribute('data-cinematic', 'true')
  await expect(page.getByRole('textbox', { name: 'Ваше действие' })).toHaveValue('Осмотреть улицу')
  expect(page.url()).toBe(sessionUrl)
})

test('режим сцены прячет и возвращает инспектор автора', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  const inspector = page.getByRole('complementary', { name: 'Инспектор сессии' })
  await expect(inspector).toBeVisible()
  await page.getByRole('button', { name: 'Скрыть интерфейс' }).click()
  await expect(inspector).toBeHidden()
  await page.mouse.click(250, 250)
  await expect(inspector).toBeVisible()
})

test('длинный инспектор прокручивается внутри экрана, не прокручивая всю студию', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  const inspector = page.getByRole('complementary', { name: 'Инспектор сессии' })
  await expect(inspector).toBeVisible()
  const measurements = await page.evaluate(() => {
    const panel = document.querySelector('.studio-inspector')!
    return {
      documentHeight: document.documentElement.scrollHeight,
      viewportHeight: window.innerHeight,
      panelScrollHeight: panel.scrollHeight,
      panelHeight: panel.clientHeight,
      panelOverflow: getComputedStyle(panel).overflowY,
    }
  })
  expect(measurements.documentHeight).toBeLessThanOrEqual(measurements.viewportHeight + 1)
  expect(measurements.panelScrollHeight).toBeGreaterThan(measurements.panelHeight)
  expect(measurements.panelOverflow).toBe('auto')
  await inspector.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await expect(inspector.getByRole('button', { name: 'Копировать ID' })).toBeInViewport()
})

test('на телефоне инспектор автора открывается поверх сцены и прокручивается внутри', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  await page.getByRole('button', { name: 'Открыть инспектор' }).click()
  const inspector = page.getByRole('complementary', { name: 'Инспектор сессии' })
  await expect(inspector).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(845)
  await inspector.evaluate((element) => { element.scrollTop = element.scrollHeight })
  await expect(inspector.getByRole('button', { name: 'Копировать ID' })).toBeInViewport()
})

test('шапка новеллы компактна и лежит поверх фона без нижней границы', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  const header = page.locator('.game-shell .game-header')
  const stage = page.getByRole('region', { name: 'Игровая сцена' })
  await expect(header).toBeVisible()
  const headerBox = await header.boundingBox()
  const stageBox = await stage.boundingBox()
  expect(headerBox).not.toBeNull()
  expect(stageBox).not.toBeNull()
  expect(headerBox!.height).toBeLessThanOrEqual(52)
  expect(stageBox!.y).toBe(headerBox!.y)
  expect(await header.evaluate((element) => getComputedStyle(element).borderBottomWidth)).toBe('0px')
  expect(await header.evaluate((element) => getComputedStyle(element).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
  const triggerBox = await page.locator('[data-slot="sidebar-trigger"]').boundingBox()
  const titleBox = await header.getByRole('heading', { name: 'Эхо неона' }).boundingBox()
  const linkBox = await header.getByRole('link', { name: 'Студия' }).boundingBox()
  expect(triggerBox).not.toBeNull()
  expect(titleBox).not.toBeNull()
  expect(linkBox).not.toBeNull()
  expect(Math.abs(titleBox!.y - triggerBox!.y)).toBeLessThanOrEqual(1)
  expect(Math.abs(linkBox!.y - triggerBox!.y)).toBeLessThanOrEqual(1)
  expect(titleBox!.height).toBe(triggerBox!.height)
  expect(linkBox!.height).toBe(triggerBox!.height)
})

test('игра сохраняется под настройками, а выбор способа сворачивания переживает перезагрузку', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionUrl = page.url()
  const sidebar = page.locator('[data-slot="sidebar"][data-side="left"]')
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await expect(sidebar).toHaveAttribute('data-collapsible', 'offcanvas')
  const triggerBox = await page.locator('[data-slot="sidebar-trigger"]').boundingBox()
  const titleBox = await page.getByTestId('story-player-route').getByRole('heading', { name: 'Эхо неона' }).boundingBox()
  expect(triggerBox).not.toBeNull()
  expect(titleBox).not.toBeNull()
  await expect.poll(async () => {
    const trigger = await page.locator('[data-slot="sidebar-trigger"]').boundingBox()
    const title = await page.getByTestId('story-player-route').getByRole('heading', { name: 'Эхо неона' }).boundingBox()
    return title && trigger ? title.x - trigger.x - trigger.width : -1
  }).toBeGreaterThanOrEqual(8)

  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toBeVisible()
  expect(page.url()).toBe(sessionUrl)
  await page.getByRole('switch', { name: 'Показывать иконки при сворачивании' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Свернуть навигацию' }).click()
  await expect(sidebar).toHaveAttribute('data-collapsible', 'icon')
  await expect(page.locator('[data-slot="sidebar-header"]')).toBeHidden()
  await page.reload()
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await expect(sidebar).toHaveAttribute('data-collapsible', 'icon')

  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('link', { name: 'Персонажи' }).click()
  await expect(page.getByRole('heading', { name: 'Аканэ' })).toBeVisible()
  await page.getByRole('link', { name: 'Настройки' }).click()
  await expect(page.getByRole('heading', { name: 'Настройки' })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('на узком экране навигация открывается поверх новеллы и закрывается после перехода', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await expect(page.locator('[data-mobile="true"]')).toBeVisible()
  await expect(page.locator('[data-slot="sidebar-trigger"]')).toHaveAttribute('aria-label', 'Свернуть навигацию')
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Настройки', exact: true })).toBeFocused()
  await page.getByRole('link', { name: 'Персонажи' }).click()
  await expect(page.getByRole('heading', { name: 'Персонажи' })).toBeVisible()
  await expect(page.locator('[data-mobile="true"]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Открыть навигацию' })).toBeVisible()
})

test('настройки поверх тестовой сцены не сбрасывают инспектор автора', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  await expect(page).toHaveURL(/\/studio\/[^/]+$/)
  const sessionUrl = page.url()
  const inspector = page.getByRole('complementary', { name: 'Инспектор сессии' })
  await expect(inspector).toBeVisible()
  await page.getByRole('button', { name: 'Открыть навигацию' }).click()
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Настройки' })).toBeVisible()
  expect(page.url()).toBe(sessionUrl)
  await page.keyboard.press('Escape')
  await expect(inspector).toBeVisible()
})
