import { expect, test } from '@playwright/test'

test('анкета закрепляется за прохождением и переживает перезагрузку', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page.getByRole('heading', { name: 'Ваш герой' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Имя' }).fill('Лена')
  await page.getByRole('textbox', { name: 'Предыстория' }).fill('Ищет сестру в городе.')
  await page.getByRole('button', { name: 'Проверить героя' }).click()
  await expect(page.getByText('Ищет сестру в городе.')).toBeVisible()
  await page.getByRole('button', { name: 'Начать историю' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionId = page.url().split('/').at(-1)
  const first = await (await page.request.get(`/api/sessions/${sessionId}`)).json()
  expect(first.protagonist.name).toBe('Лена')
  expect(first.protagonist.biography).toBe('Ищет сестру в городе.')
  await page.getByRole('button', { name: 'Настройки прохождения' }).click()
  await page.getByRole('spinbutton', { name: 'Возраст' }).fill('24')
  await page.getByRole('textbox', { name: 'Характер' }).fill('Упорная')
  await page.getByRole('textbox', { name: 'Внешность' }).fill('Короткие тёмные волосы')
  await page.getByRole('button', { name: 'Сохранить героя в каталог' }).click()
  await expect(page.getByText('Герой Лена сохранён в каталоге.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('textbox', { name: 'Ваше действие' }).fill('Осмотреть улицу')
  await page.getByRole('button', { name: 'Отправить' }).click()
  await expect(page.getByText(/Я ждала этого вопроса/)).toBeVisible()
  await page.reload()
  const restored = await (await page.request.get(`/api/sessions/${sessionId}`)).json()
  expect(restored.protagonist).toEqual(first.protagonist)
  expect(restored.latest_turn.segments.some((part: { kind: string; character_id?: string }) => part.kind === 'dialogue' && part.character_id === restored.protagonist.source_character_id)).toBe(false)
})

test('герой из каталога закрепляется по точной ревизии', async ({ page }) => {
  const createdResponse = await page.request.post('/api/characters', { data: {
    name: 'Марк Тестовый', gender: 'male', age: 27, personality: 'Спокойный', appearance: 'Тёмный плащ', biography: 'Приехал в город.', speech: '',
  } })
  expect(createdResponse.ok()).toBeTruthy()
  const created = await createdResponse.json()
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await page.getByRole('button', { name: 'Из каталога' }).click()
  await page.getByRole('button', { name: 'Марк Тестовый' }).click()
  await page.getByRole('button', { name: 'Проверить героя' }).click()
  await page.getByRole('button', { name: 'Начать историю' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionId = page.url().split('/').at(-1)
  const session = await (await page.request.get(`/api/sessions/${sessionId}`)).json()
  expect(session.protagonist.source_character_id).toBe(created.character_id)
  expect(session.protagonist.source_revision_id).toBe(created.current_revision_id)
  const revision = await page.request.post(`/api/characters/${created.character_id}/revisions`, { data: {
    name: 'Марк Изменённый', gender: 'male', age: 28, personality: 'Суровый', appearance: 'Другой плащ', biography: 'Иная история.', speech: '',
  } })
  expect(revision.ok()).toBeTruthy()
  await page.reload()
  const restored = await (await page.request.get(`/api/sessions/${sessionId}`)).json()
  expect(restored.protagonist.name).toBe('Марк Тестовый')
  expect(restored.protagonist.source_revision_id).toBe(created.current_revision_id)
})
