import { expect, test } from '@playwright/test'

test('смена модели в настройках сохраняет ту же сессию и используется следующим ходом', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionId = page.url().split('/').at(-1)
  await page.getByRole('button', { name: 'Настройки прохождения' }).click()
  await page.getByRole('combobox', { name: 'Модель Ollama' }).click()
  await page.getByRole('option', { name: 'gemma4-local:32k' }).click()
  await page.getByRole('button', { name: 'Применить модель' }).click()
  await expect(page.getByRole('dialog')).toContainText('Сейчас: gemma4-local:32k')
  await page.keyboard.press('Escape')
  await page.getByRole('textbox', { name: 'Ваше действие' }).fill('Осмотреть комнату')
  const turnResponse = page.waitForResponse((response) => response.url().endsWith(`/api/sessions/${sessionId}/turns`))
  await page.getByRole('button', { name: 'Отправить' }).click()
  expect((await (await turnResponse).json()).model_id).toBe('gemma4-local:32k')
  await expect(page.getByRole('button', { name: 'Отменить ход' })).toBeEnabled()
  const response = await page.request.get(`/api/sessions/${sessionId}`)
  expect(response.ok()).toBeTruthy()
  expect((await response.json()).model_id).toBe('gemma4-local:32k')
  await page.reload()
  await page.getByRole('button', { name: 'Настройки прохождения' }).click()
  await expect(page.getByRole('dialog')).toContainText('Сейчас: gemma4-local:32k')
})

test('игрок отменяет ход, выбирает другую ветку и восстанавливает её после перезагрузки', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Начать новую игру' }).click()
  await expect(page).toHaveURL(/\/play\/[^/]+$/)
  const sessionUrl = page.url()
  await expect(page.getByRole('heading', { name: 'Эхо неона' })).toBeVisible()

  await page.getByRole('button', { name: 'Варианты (3)' }).click()
  await page.getByRole('button', { name: 'Спросить о веере' }).click()
  await expect(page.getByRole('img', { name: /Аканэ.*С веером/ })).toBeVisible()
  await page.getByRole('button', { name: 'Показать полностью' }).click()
  await expect(page.getByText(/Я ждала этого вопроса/)).toBeVisible()
  await page.getByRole('button', { name: 'Отменить ход' }).click()
  await expect(page.getByRole('button', { name: 'Отменить ход' })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Ваше действие' }).fill('Осмотреть комнату')
  await page.getByRole('button', { name: 'Отправить' }).click()
  await expect(page.getByRole('button', { name: 'Отменить ход' })).toBeEnabled()
  await page.goto('/')
  await page.getByRole('tab', { name: /Начатые/ }).click()
  await expect(page.getByRole('button', { name: 'Продолжить' })).toHaveCount(1)
  const saveCard = page.locator(`[data-session-id="${sessionUrl.split('/').at(-1)}"]`)
  await expect(saveCard.getByText('Сцена: Ночной перекрёсток')).toBeVisible()
  await saveCard.getByRole('button', { name: 'Продолжить' }).click()
  await expect(page).toHaveURL(sessionUrl)
  await expect(page.getByText(/Я ждала этого вопроса/)).toBeVisible()

  await page.reload()
  await expect(page.getByRole('img', { name: /Аканэ.*С веером/ })).toBeVisible()
  await page.getByRole('button', { name: 'Показать полностью' }).click()
  await expect(page.getByText(/Я ждала этого вопроса/)).toBeVisible()
  await page.getByTestId('story-player-route').getByRole('link', { name: 'Студия' }).click()
  await expect(page.getByRole('complementary', { name: 'Инспектор сессии' }).getByText('v4')).toBeVisible()
  await expect(page.locator('[data-field="prompt-version"]')).toHaveText('first-playable-v1')
  await expect(page.locator('[data-field="last-action"]')).toHaveText('Осмотреть комнату')
})
