[alembic]
script_location = %(here)s/migrations
prepend_sys_path = .
path_separator = os
sqlalchemy.url = sqlite:///data/visual-novel.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[formatters]
keys = generic

[logger_root]
level = WARN
handlers =
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
